# Generated by Django 4.2.20 on 2025-03-18 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eld_log', '0002_rename_total_miles_driving_today_eldlog_total_driving_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timing',
            name='eld_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timings', to='eld_log.eldlog'),
        ),
    ]
