# Generated by Django 4.2.20 on 2025-03-18 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eld_log', '0003_alter_timing_eld_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eldlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, unique=True),
        ),
    ]
