# Generated by Django 4.2.20 on 2025-03-18 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eld_log', '0004_alter_eldlog_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eldlog',
            old_name='main_soffice_address',
            new_name='main_office_address',
        ),
        migrations.AlterField(
            model_name='eldlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
