# Generated by Django 4.2.20 on 2025-03-19 14:00

from django.db import migrations, models
import eld_log.models


class Migration(migrations.Migration):

    dependencies = [
        ('eld_log', '0005_rename_main_soffice_address_eldlog_main_office_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eldlog',
            name='time_line',
            field=models.ImageField(blank=True, upload_to=eld_log.models.file_location),
        ),
    ]
